name: Run JUnit Tests (Maven)

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests - Identifier Program
        run: |
          cd identifier-program
          mvn -B test